---
title: "Module 14"
author: "Emily Yang"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(curl)
f <- curl("https://raw.githubusercontent.com/fuzzyatelin/fuzzyatelin.github.io/master/AN588_Fall23/zombies.csv")
z <- read.csv(f, header = TRUE, sep = ",", stringsAsFactors = TRUE)

m <- lm(data = z, height ~ gender)
summary(m)
```


```{r}
z$occupation <- "temp"
levels(z$major)
row(data.frame(levels(z$major)))

z$occupation[row(data.frame(levels(z$major))) %in% c(1, 2, 3, 5, 6, 14, 15,
    16, 18, 21, 23)] <- "natural science"
z$occupation[row(data.frame(levels(z$major))) %in% c(7, 8, 12, 17, 19, 22)] <- "logistics"
z$occupation[row(data.frame(levels(z$major))) %in% c(4, 18, 20)] <- "engineering"
z$occupation[row(data.frame(levels(z$major))) %in% c(9, 10, 11, 13, 24, 25,
    26)] <- "other"
z$occupation <- as.factor(z$occupation)
levels(z$occupation)

m <- lm(data = z, zombies_killed ~ occupation)
summary(m)

plot(data = z, zombies_killed ~ occupation)
p <- 1 - pf(0.526, df1 = 3, df2 = 996)  # F test
p

```

## One-Way Anova

``` {r}
m <- aov(data = z, zombies_killed ~ occupation)
summary(m)
plot(m)

library(dplyr)
f <- curl("https://raw.githubusercontent.com/fuzzyatelin/fuzzyatelin.github.io/master/AN588_Fall21/gibbon-femurs.csv")
d <- read.csv(f, header = TRUE, sep = ",", stringsAsFactors = TRUE)
d$age <- factor(d$age, levels = c("inf", "juv", "subadult", "adult"))  #this reorders the age levels so that they're in order
head(d) 
hist(d$femur.length) # not normal

plot(data = d, femur.length ~ age)
means <- summarise(group_by(d, age), mean(femur.length))  # calculate average by group
points(1:4, means$`mean(femur.length)`, pch = 4, cex = 1.5)  # add means to plot
```

## Post-hoc Test

```{r}
pairwise.t.test(d$femur.length, d$age, p.adj = "bonferroni") # Estimate between two groups without need for correction
m <- aov(d$femur.length ~ d$age)
posthoc <- TukeyHSD(m, "d$age", conf.level = 0.95)
posthoc  # all age-sex classes differ
```


# Multiple Anova

```{r}
means <- summarise(group_by(d, age, sex), mean(femur.length))

m1 <- aov(data = d, femur.length ~ age * sex) # The first one entered soaks up variance
summary(m1)
m2 <- aov(data = d, femur.length ~ sex * age)
summary(m2)
```
